---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: resource-jupyter

outputs:
- name: web-docker-image

run:
  path: ./resource-jupyter/.concourse/tasks/build-jupyter-container.sh
