---
platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: dind}

inputs:
- name: resource-jupyter

run:
  path: resource-jupyter/.concourse/tasks/deploy-jupyter-container.sh
